---
title: "Final Project workbook"
output: html_notebook
---

```{r include=FALSE}
# load libraries
library(tidyverse)
library(janitor)
library(jsonlite)
library(here)
library(lubridate)
library(leaflet)
library(tsibbledata)
library(tsibble)
library(elevatr)
library(rgdal)
library(circlize)
library(ggraph)



```

```{r}
# Load in data
hires_2019_clean <- read_csv('../clean_data/hires_2019_clean.csv')

```



```{r}
# number of stations in total: 164
hires_2019_clean %>% 
  distinct(start_station_id) %>% 
  count()

hires_2019_clean %>% 
  distinct(end_station_id) %>% 
  count()
```


```{r}
# visualising use by month
hires_2019_clean %>% 
  mutate(month = month(start_date, label = TRUE), .before = 1) %>% 
  group_by(month) %>% 
  summarise(count = n()) %>%
  ggplot() +
  aes(x = month, y = count) +
  geom_col(fill = "#F27F1B") +
  geom_text(aes(label = count), vjust = 2, colour = "white", size = 3.5) +
  labs(x = "\nMonth",
       y = "Number of journeys\n",
       title = "Total number of bike journeys by month (2019)\n") +
  scale_y_discrete(expand = c(0,1), limits = c(0, 5000, 10000, 15000, 20000)) +
  theme_minimal() +
  theme(title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
```


```{r}
hires_2019_clean %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addTiles(providers$CartoDB.Positron) %>%
  addCircles(lng = ~start_station_longitude,
             lat = ~start_station_latitude,
             popup = ~paste0("Station ID: ", start_station_name,
                             "<br>Elevation (m): ", start_elevation))
```


```{r}
# top 10 start and end stations
hires_2019_clean %>% 
  select(start_station_id, start_station_name) %>% 
  count(start_station_id, start_station_name) %>% 
  arrange(desc(n)) %>% 
  head(10)

hires_2019_clean %>% 
  select(end_station_id, end_station_name) %>% 
  count(end_station_id, end_station_name) %>% 
  arrange(desc(n)) %>%
  head(10)
```


```{r}
hires_2019_clean %>% 
  select(start_station_id, end_station_id) %>% 
  filter(start_station_id == c("248", "259", "265", "262", "289", "257", "247", "249", "264", "290"), 
         end_station_id == c("250", "248", "259", "366", "265", "262", "257", "264", "1026", "358")) %>% 
  chordDiagram()
  
  #chordDiagram(annotationTrack = c("name", "grid"))
```

```{r}
hires_2019_clean %>% 
  select(start_station_id, end_station_id) %>%
  filter(start_station_id == c("248", "259", "265", "262", "289", "257", "247", "249", "264", "290"), 
         end_station_id == c("250", "248", "259", "366", "265", "262", "257", "264", "1026", "358")) %>% 
  ggraph(layout = "linear") + 
  geom_edge_arc(edge_colour = "black", edge_alpha = 0.3, edge_width = 0.2) +
  geom_node_point(color = "#F27F1B", size = 10) +
  geom_node_text(aes(label = name), repel = FALSE, size = 3, nudge_y = 0, colour = "white") +
  labs(title = "Journeys between most popular stations\n\n") +
  theme_void() +
  theme(title = element_text(size = 12),
        legend.position = "none",
        plot.margin = unit(rep(1, 4), "cm"))
```
### Journeys based on elevation

```{r}
# downhill vs uphill vs flat journeys
# based on elevation of start and end stations

# 68153 downhill journeys
hires_2019_clean %>% 
  filter(elevation_diff < 0) %>% 
  count()

# 43499 uphill journeys
hires_2019_clean %>% 
  filter(elevation_diff > 0) %>% 
  count()

# 12032 flat journeys
hires_2019_clean %>% 
  filter(elevation_diff == 0) %>% 
  count()
```

### Journeys based on weather

```{r}
# journeys based on rainfall
# based on daily precipitation
hires_2019_clean %>% 
  filter(rainfall_mm >= 1) %>% 
  count()

hires_2019_clean %>% 
  filter(rainfall_mm < 1) %>% 
  count()
```

```{r}
hires_2019_clean %>% 
  select(start_date, rainfall_mm) %>% 
  ggplot() +
  geom_line(aes(start_date, rainfall_mm), col = "blue") +
  geom_hline(yintercept = 1, col="red") +
  labs(x = "\nDate",
       y = "Rainfall (mm)\n",
       title = "Edinburgh's daily rainfall in 2019",
       subtitle = "(Red line at 1mm, above which class as rainy day)") +
  theme_minimal() +
  theme(title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))
```

```{r}
hires_2019_clean %>% 
  filter(start_time > "06:00:00", start_time < "07:00:00")
```


